#!/bin/sh

# Copyright 2025, Pouria Rezaei <Pouria.rz@outlook.com>

# Part of RedOrder, handling Debian
# (Most-likely due me hating Ubuntu)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

set -e

mirror="http://ftp.uk.debian.org"
version="forky"

if [ "$(id -u)" -ne 0 ]; then
	echo "This script must be run as root."
	exit 1
fi

# For some reason.. my method won't work with old env.
if [ ! "$(uname -r | cut -d. -f1)" -ge 6 ]; then
	echo "Sorry.. kernel is outdated for this script."
	exit 1
fi

if ! command -v wget >/dev/null 2>&1; then
	echo "This script requires wget."
	exit 1
fi

docker_install() {
	local ARCH VER VER_BX

	ARCH=$(uname -m)
	VER=$(wget -qO- https://download.docker.com/linux/static/stable/x86_64/ | \
          grep -oE 'docker-[0-9]+\.[0-9]+\.[0-9]+\.tgz' | \
          sort -V | tail -n1 | cut -d- -f2 | cut -d. -f1-3)

	VER_BX=$(wget -qO- https://api.github.com/repos/docker/buildx/releases/latest \
          | grep '"tag_name"' | cut -d'"' -f4)

	if [ ! "$ARCH" = "x86_64" ]; then
		echo "This package is only for $ARCH."
		exit 1
	fi

	rm -rf /tmp/* || true

	wget -q "https://download.docker.com/linux/static/stable/$ARCH/docker-${VER}.tgz" \
		-O /tmp/docker.tgz
	# Docker main
	tar xzf /tmp/docker.tgz -C /tmp
	install -m0755 /tmp/docker/* /usr/local/bin/

	wget \
     "https://github.com/docker/buildx/releases/download/$VER_BX/buildx-${VER_BX}.linux-amd64" \
	 	-O /tmp/docker-buildx
	install -m0755 /tmp/docker-buildx /usr/local/bin/docker-buildx

	cat > /etc/systemd/system/docker.service <<-EOF
	[Unit]
	Description=Docker Service
	After=network-online.target containerd.service

	[Service]
	Type=notify
	ExecStart=/usr/local/bin/dockerd
	Restart=always
	Delegate=yes

	[Install]
	WantedBy=multi-user.target

	EOF

	systemctl daemon-reload
	systemctl enable docker --now

	getent group docker >/dev/null || groupadd docker
	usermod -aG docker "$USER"
}

if ! command -v docker >/dev/null 2>&1; then
	echo "Let me install docker ..."
	docker_install 2>/dev/null || exit 1
fi

if ! command -v rsync >/dev/null 2>&1 ; then
	echo "rsync required to install extracted Slackware tree."
	exit 1
fi

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/games"

extract_and_prepare() {
	rm -rf /tmp/build /Debian
	mkdir -p /tmp/build /Debian
	# Extract base from Docker
	cat > /tmp/build/Dockerfile <<-INIT
	FROM debian:$version AS builder
	USER root

	RUN apt update && apt -y install debootstrap
	RUN mkdir -p /mnt && \
		debootstrap --arch amd64 \
		--include=sudo,dbus,bash,vim,wget,ca-certificates,zstd \
		$version /mnt $mirror/debian

	FROM scratch
	COPY --from=builder /mnt /

	CMD ["/bin/bash"]
	INIT

	( cd /tmp/build
	if ! command -v docker-buildx >/dev/null 2>&1; then
		DOCKER_BUILDKIT=1 \
			docker build -t base_sys .
	else
		docker-buildx build -t base_sys . || \
			echo "This script need's buildx"
	fi )

	docker create --name deb_tmp base_sys
	docker export deb_tmp -o /tmp/base.tar
	docker rm -f deb_tmp
	docker rmi base_sys
	tar -xf /tmp/base.tar -C /Debian
	rm -f /tmp/base.tar

	echo "nameserver 1.1.1.1" > /Debian/etc/resolv.conf
}

backup_old_files() {
	cp -fL /etc/hostname /etc/localtime /Debian/etc/ \
		2>/dev/null || true
	# Backup the partitions scheme
	# sgdisk --backup='/tmp/partitions.map' $DISK
}

cleanup() {
	rm -rf /boot/efi/* 2>/dev/null || true
	rm -f /boot/* 2>/dev/null || true
	find / \( -type f -o -type d \) -exec chattr -i {} + 2>/dev/null || true
}

overwrite_system() {
	# Galactic smash
	rsync -aHAX --numeric-ids --delete-after --exclude=/dev/** --exclude=/home/** \
		--exclude=/proc/** --exclude=/sys/** --exclude=/Debian/** \
		--exclude=/efi/** --exclude=/boot/** --exclude=/tmp/** \
		/Debian/ / || true

	cleanup
	rm -rf /Debian >/dev/null 2>&1 || true

	cat > /etc/apt/sources.list <<-MGM
	deb $mirror/debian/ $version contrib main non-free non-free-firmware

	deb $mirror/debian/ ${version}-updates contrib main non-free non-free-firmware

	deb $mirror/debian/ ${version}-proposed-updates contrib main non-free non-free-firmware

	deb $mirror/debian/ ${version}-backports contrib main non-free non-free-firmware

	#deb $mirror/debian-security/ ${version}-security contrib main non-free non-free-firmware

	MGM
	unset mirror version

	# For locale
	cat > /etc/locale.gen <<-LCL
	en_GB.UTF-8 UTF-8
	en_US.UTF-8 UTF-8

	LCL

	update-ca-certificates
	export DEBIAN_FRONTEND=noninteractive

	# Not too raw.. I still want ubuntu stuff a bit
	apt update
	apt dist-upgrade --auto-remove -y

	apt install -y base-files base-passwd bash bash-completion bzip2 coreutils \
		dash debconf debianutils diffutils dpkg findutils gnupg grep gzip hostname \
		init-system-helpers iproute2 iputils-ping less logsave lsof mawk \
		ncurses-base netbase netcat-openbsd passwd perl-base sed sensible-utils \
		tar util-linux zlib1g initramfs-tools initramfs-tools-core kmod \
		linux-base linux-image-amd64 systemd-sysv adduser bind9-host \
		bridge-utils btrfs-progs curl dnsutils ethtool ifupdown isc-dhcp-client \
		isc-dhcp-common libnss-myhostname libpam-systemd net-tools netplan.io \
		openssh-client openssh-server tcpdump vlan wget at bc binutils \
		binutils-x86-64-linux-gnu bsdmainutils byobu command-not-found cron dbus \
		distro-info-data dosfstools ed file finger htop info iotop lshw ltrace \
		man-db manpages mdadm mtr-tiny nano parted pciutils powermgmt-base \
		psmisc python3 python3-minimal readline-common rsyslog screen strace \
		sysstat tasksel tmux traceroute usbutils uuid-runtime vim \
		wamerican x11-common xkb-data cryptsetup cryptsetup-initramfs dmsetup \
		efibootmgr gdisk lvm2 multipath-tools nvme-cli open-iscsi alsa-utils \
		rsync sg3-utils smartmontools squashfs-tools open-vm-tools \
		xfsprogs zfsutils-linux apparmor apt apt-utils ca-certificates \
		gnupg gnupg2 gpgconf openssl p11-kit publicsuffix \
		python3-apt python3-requests python3-setuptools vim-scripts \
		python3-urllib3 python3-yaml sudo acpid wamerican wamerican-large \
		anacron dbus-broker desktop-file-utils dnsmasq-base \
		dpkg-dev eject fuse3 git git-man grub-common linux-headers-amd64 \
		grub-efi-amd64 grub2-common hdparm hwdata irqbalance kpartx lm-sensors \
		logrotate lrzip lxc make manpages-dev memtest86+ modemmanager \
		moreutils mosh ncdu fastfetch netcat-traditional nfs-common \
		open-vm-tools openvpn os-prober passwd pastebinit patch pciutils pigz \
		plymouth pm-utils popularity-contest powertop ppp pptp-linux procps \
		pv python3-cffi-backend python3-chardet python3-configobj \
		python3-cryptography python3-dbus python3-debian python3-distro \
		python3-gi python3-idna python3-jinja2 python3-jsonschema python3-lxml \
		python3-newt python3-oauthlib python3-paramiko pkg-config \
		python3-pip python3-ply python3-psutil python3-pyasn1 \
		python3-urwid qemu-guest-agent quota radvd rpcbind ruby-net-telnet \
		rpm rpm2cpio rsnapshot rtkit ruby ruby-json ruby-minitest \
		ruby-power-assert ruby-test-unit ruby-xmlrpc runc rxvt-unicode safe-rm \
		samba-common samba-common-bin sane-utils sbcl scdaemon schedtool scrot \
		seabios secure-delete sgml-base shared-mime-info shellcheck shim-signed \
		smartmontools socat sqlite3 ssh-import-id systemd-coredump \
		ssl-cert stress stunnel4 subversion sysbench sysfsutils \
		systemd-journal-remote systemd-timesyncd sysvinit-utils t1utils \
		testdisk texinfo texlive-base texlive-binaries traceroute telnet \
		texlive-fonts-recommended texlive-latex-base texlive-latex-recommended \
		thin-provisioning-tools tigervnc-standalone-server tree w3m-img \
		u-boot-tools udisks2 ufw uget unar vim-runtime vim vbetool \
		unbound unrar-free unzip usb-modeswitch usbutils uuid-runtime \
		vde2 virt-what vorbis-tools w3m

	# Making sure one last time
	dpkg --configure -a
}

configure_network() {
	local dev ipaddr prefix gateway net_conf

	dev=$(ls /sys/class/net | grep -Ev '^(lo|docker|veth|br-|virbr|vmnet|zt|wg)' | head -n1)
	ipaddr=$(ip -4 -o addr show dev "$dev" scope global | awk '{print $4; exit}')
	gateway=$(ip -4 route show default | awk '/default/ {print $3; exit}')
	net_conf="/etc/netplan/00_default.yaml"

	mkdir -p /etc/netplan
	rm -rf /etc/netplan/{.*,*} || true

	cat > /etc/network/interfaces <<-EOF
	auto lo
	iface lo inet loopback

	allow-hotplug $dev
	iface $dev inet dhcp

	EOF

	if [ -n "$ipaddr" ] && [ -n "$gateway" ]; then
		prefix=${ipaddr#*/}
		cat >"$net_conf" <<-EOF
		network:
		  version: 2
		  renderer: networkd
		  ethernets:
		    ${dev}:
		      addresses:
		        - ${ipaddr}
		      gateway4: ${gateway}
		      nameservers:
		        addresses: [1.1.1.1]
		EOF
	else
		cat >"$net_conf" <<-EOF
		network:
		  version: 2
		  renderer: networkd
		  ethernets:
		    ${dev}:
		      dhcp4: true
		EOF
	fi

	netplan generate
	netplan apply >/dev/null 2>&1 || true
}

configure_bootloader() {
	local root_dev needs_lvm2

	root_dev=$(findmnt -no SOURCE / 2>/dev/null)
	needs_lvm2=0

	if findmnt /efi >/dev/null 2>&1; then
		umount -l /efi
		rm -rf /efi
		sed -i 's/\/efi/\/boot\/efi/' /etc/fstab || true
	fi

	case $root_dev in
	/dev/mapper/*) needs_lvm2=1 ;;
	esac

	if [ $needs_lvm2 -eq 1 ] && [ -f /etc/lvm/lvm.conf ]; then
		sed -i.bak 's/use_lvmetad = 1/use_lvmetad = 0/g' /etc/lvm/lvm.conf 2>/dev/null
	fi

	grub-install --force --removable --target=x86_64-efi --efi-directory=/boot/efi
	grub-mkconfig -o /boot/grub/grub.cfg 2>/dev/null

	if [ -f /etc/lvm/lvm.conf.bak ]; then
		mv /etc/lvm/lvm.conf.bak /etc/lvm/lvm.conf 2>/dev/null
	fi
}

finalize() {
	if [ -d /etc/ssh/sshd_config.d ]; then
		printf 'PermitRootLogin yes\nPasswordAuthentication yes\n' > /etc/ssh/sshd_config.d/50-Debian.conf
	else
		if grep -q '^#PermitRootLogin' /etc/ssh/sshd_config 2>/dev/null; then
			sed -i '/^#PermitRootLogin\s/s/.*/PermitRootLogin yes/' /etc/ssh/sshd_config 2>/dev/null
		else
			grep -q '^PermitRootLogin' /etc/ssh/sshd_config 2>/dev/null || printf 'PermitRootLogin yes\n' >> /etc/ssh/sshd_config
		fi
	fi

	echo "\nfastfetch\n" >> /etc/profile
	echo 'root:0v3rk1ll' | chpasswd

	cat <<-EOF
	Hey there,
	This machine has been squashed with new Debian distro.

	Recommended actions (on the VM host console):
	# sync ; reboot -f

	After reboot you should be able to login as root with '0v3rk1ll'
	Change it later how you see it fit ;-)
	EOF
}

choose_option() {
	case "$1" in
		1|--debian)
			printf 'Installing Debian %s..\n' "$version"
			return 0
			;;
		*)
			return 1
			;;
	esac
}

show_menu() {
	cat <<-EOF
Supported distributions:
1) Debian $version    (--debian)

Usage: $0 [option_number|--option_name]
EOF
}

if [ -n "$1" ]; then
	if ! choose_option "$1"; then
		printf 'Invalid option: %s\n' "$1"
		show_menu
		exit 1
	fi
else
	choose_option 1
fi

cd /
extract_and_prepare
backup_old_files
overwrite_system
configure_network
configure_bootloader
finalize

unset mirror version
